services:
  - type: web
    name: tabison-suppliers-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MPESA_BUSINESS_SHORT_CODE
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_ENVIRONMENT
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: PAYPAL_MODE
        value: sandbox
      - key: BASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true